#sync-config.yml
# Optimized configuration for advanced-git-sync action
# When you have gitlab.sync.[entity].enabled: true, it means those entities will be synced FROM GitHub TO GitLab
gitlab:
  enabled: true
  owner: vikshan # GitLab username
  sync:
    branches:
      enabled: true
      protected: true
      pattern: "*"
    pullRequests:
      enabled: true
      autoMerge: false
      labels: ["synced", "github-origin"]
    issues:
      enabled: true
      syncComments: false
      labels: ["synced", "github-origin"]
    releases:
      enabled: true
    tags:
      enabled: true

# When you have github.sync.[entity].enabled: true, it means those entities will be synced FROM GitLab TO GitHub
github:
  enabled: true
  sync:
    branches:
      enabled: true
      protected: true
      pattern: "*"
    pullRequests:
      enabled: true
      autoMerge: false
      labels: ["synced", "gitlab-origin"]
    issues:
      enabled: true
      syncComments: false
      labels: ["synced", "gitlab-origin"]
    releases:
      enabled: true
    tags:
      enabled: true
