# When you have gitlab.sync.[entity].enabled: true, entities will be synced FROM GitLab to GitHub
gitlab:
  enabled: true
  owner: vikshan # GitLab username
  sync:
    branches:
      enabled: true
      protected: true
      pattern: "*"
      historySync:
        enabled: true
        strategy: "merge-timelines"
        createMergeCommits: true
        mergeMessage: "Sync: Merge timeline from {source} to {target}"

    pullRequests:
      enabled: true
      autoMerge: true
      labels: ["synced"]
      comments:
        enabled: true # Enable to sync PR comments with attribution
        attribution:
          includeAuthor: true
          includeTimestamp: true
          includeSourceLink: true
          format: "quoted" # quoted | inline | minimal
        handleUpdates: true
        preserveFormatting: true
        syncReplies: true

    issues:
      enabled: true
      labels: ["synced"]
      comments:
        enabled: true # Enable to sync issue comments with attribution
        attribution:
          includeAuthor: true
          includeTimestamp: true
          includeSourceLink: true
          format: "quoted" # quoted | inline | minimal
        handleUpdates: true
        preserveFormatting: true
        syncReplies: true

    releases:
      enabled: true
      divergentCommitStrategy: "skip"
      latestReleaseStrategy: "point-to-latest"
      skipPreReleases: false
      pattern: "*"
      includeAssets: true

    tags:
      enabled: true # automatically enabled if releases = true
      divergentCommitStrategy: "skip"
      pattern: "*"

# When you have github.sync.[entity].enabled: true, entities will be synced FROM GitHub to GitLab
github:
  enabled: true
  sync:
    branches:
      enabled: true
      protected: true
      pattern: "*"
      historySync:
        enabled: true
        strategy: "merge-timelines"
        createMergeCommits: true
        mergeMessage: "Sync: Merge timeline from {source} to {target}"

    pullRequests:
      enabled: true
      autoMerge: true
      labels: ["synced"]
      comments:
        enabled: true # Enable to sync PR comments with attribution
        attribution:
          includeAuthor: true
          includeTimestamp: true
          includeSourceLink: true
          format: "quoted" # quoted | inline | minimal
        handleUpdates: true
        preserveFormatting: true
        syncReplies: true

    issues:
      enabled: true
      labels: ["synced"]
      comments:
        enabled: true # Enable to sync issue comments with attribution
        attribution:
          includeAuthor: true
          includeTimestamp: true
          includeSourceLink: true
          format: "quoted" # quoted | inline | minimal
        handleUpdates: true
        preserveFormatting: true
        syncReplies: true

    releases:
      enabled: true
      divergentCommitStrategy: "skip"
      latestReleaseStrategy: "point-to-latest"
      skipPreReleases: false
      pattern: "*"
      includeAssets: true

    tags:
      enabled: true # automatically enabled if releases = true
      divergentCommitStrategy: "skip"
      pattern: "*"
