name: "Configure Container Registries"
description: "Sets up authentication for GitHub, GitLab, and Docker Hub container registries"

inputs:
  github-pat:
    description: "GitHub PAT for container registry"
    required: true
  gitlab-token:
    description: "GitLab token for container registry"
    required: true
  dockerhub-username:
    description: "Docker Hub username"
    required: true
  dockerhub-token:
    description: "Docker Hub access token"
    required: true
  github-registry:
    description: "GitHub container registry URL"
    required: true
  gitlab-registry:
    description: "GitLab container registry URL"
    required: true
  github-username:
    description: "GitHub username"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.github-registry }}
        username: ${{ inputs.github-username }}
        password: ${{ inputs.github-pat }}

    - name: Log in to GitLab Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.gitlab-registry }}
        username: oauth2
        password: ${{ inputs.gitlab-token }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}
