# Use the same image as devcontainer for consistency
image: ghcr.io/iamvikshan/devcontainers/bun-node:latest

# Configure VS Code extensions
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - GitHub.copilot
    - esbenp.prettier-vscode
    - eamodio.gitlens
    - oven.bun-vscode
    - ms-azuretools.vscode-docker

# Configure ports for development servers
ports:
  - name: Development Server
    port: 3000
    onOpen: open-preview
  - name: Vite Dev Server
    port: 5173
    onOpen: open-preview
  - name: Docker Registry
    port: 5000
    onOpen: ignore

# Setup tasks
tasks:
  - name: Install Docker
    init: |
      # Install Docker since Gitpod doesn't have it preloaded
      sudo apt-get update
      sudo apt-get install -y docker.io docker-compose
      sudo systemctl start docker
      sudo systemctl enable docker
      sudo usermod -aG docker $USER
      # Verify Docker installation
      docker --version
      docker-compose --version

  - name: Setup Project
    init: |
      echo "🔧 Setting up DevContainers project..."
      # Install dependencies
      bun install
      # Verify setup
      echo "✅ Project setup complete!"

  - name: Development
    command: |
      echo "🚀 DevContainers project ready!"
      echo ""
      echo "Available commands:"
      echo "  bun run sync-sizes     - Update image sizes"
      echo "  bun run check-updates  - Check for base image updates"
      echo "  bun run analyze-sizes  - Analyze image sizes"
      echo "  bun run build-all      - Build all images (requires Docker)"
      echo ""
      echo "📚 Documentation:"
      echo "  README.md              - Main documentation"
      echo "  docs/SETUP.md          - Setup guide"
      echo "  docs/BUILD_COMMANDS.md - Build instructions"
