name: "Build Container Images"
description: "Builds and pushes container images to registries"

inputs:
  version:
    description: "Release version"
    required: true
  github-registry:
    description: "GitHub container registry URL"
    required: true
  gitlab-registry:
    description: "GitLab container registry URL"
    required: true
  gitlab-project-path:
    description: "GitLab project path"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build and push base containers
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        GITHUB_REGISTRY: ${{ inputs.github-registry }}
        GITLAB_REGISTRY: ${{ inputs.gitlab-registry }}
        GITLAB_PROJECT_PATH: ${{ inputs.gitlab-project-path }}
      run: |
        for dir in base/*/; do
          devcontainer_name=$(basename "$dir")
          if [ -f "$dir/.devcontainer/Dockerfile" ]; then
            # Build the image
            docker buildx build \
              --file "$dir/.devcontainer/Dockerfile" \
              --tag "${GITHUB_REGISTRY}/${{ github.repository }}/${devcontainer_name}:v${VERSION}" \
              --tag "${GITHUB_REGISTRY}/${{ github.repository }}/${devcontainer_name}:latest" \
              --tag "${GITLAB_REGISTRY}/${GITLAB_PROJECT_PATH}/${devcontainer_name}:v${VERSION}" \
              --tag "${GITLAB_REGISTRY}/${GITLAB_PROJECT_PATH}/${devcontainer_name}:latest" \
              "$dir/.devcontainer"

            # Push the image to GitHub registry
            docker push "${GITHUB_REGISTRY}/${{ github.repository }}/${devcontainer_name}:v${VERSION}"
            docker push "${GITHUB_REGISTRY}/${{ github.repository }}/${devcontainer_name}:latest"

            # Push the image to GitLab registry
            docker push "${GITLAB_REGISTRY}/${GITLAB_PROJECT_PATH}/${devcontainer_name}:v${VERSION}"
            docker push "${GITLAB_REGISTRY}/${GITLAB_PROJECT_PATH}/${devcontainer_name}:latest"
          fi
        done

    - name: Build and push Ubuntu containers
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        GITHUB_REGISTRY: ${{ inputs.github-registry }}
        GITLAB_REGISTRY: ${{ inputs.gitlab-registry }}
        GITLAB_PROJECT_PATH: ${{ inputs.gitlab-project-path }}
      run: |
        for dir in base/ubuntu/*/; do
          devcontainer_name=$(basename "$dir")
          if [ -f "$dir/Dockerfile" ]; then
            # Build the image
            docker buildx build \
              --file "$dir/Dockerfile" \
              --tag "${GITHUB_REGISTRY}/${{ github.repository }}/ubuntu-${devcontainer_name}:v${VERSION}" \
              --tag "${GITHUB_REGISTRY}/${{ github.repository }}/ubuntu-${devcontainer_name}:latest" \
              --tag "${GITLAB_REGISTRY}/${GITLAB_PROJECT_PATH}/ubuntu-${devcontainer_name}:v${VERSION}" \
              --tag "${GITLAB_REGISTRY}/${GITLAB_PROJECT_PATH}/ubuntu-${devcontainer_name}:latest" \
              "$dir"

            # Push the image to GitHub registry
            docker push "${GITHUB_REGISTRY}/${{ github.repository }}/ubuntu-${devcontainer_name}:v${VERSION}"
            docker push "${GITHUB_REGISTRY}/${{ github.repository }}/ubuntu-${devcontainer_name}:latest"

            # Push the image to GitLab registry
            docker push "${GITLAB_REGISTRY}/${GITLAB_PROJECT_PATH}/ubuntu-${devcontainer_name}:v${VERSION}"
            docker push "${GITLAB_REGISTRY}/${GITLAB_PROJECT_PATH}/ubuntu-${devcontainer_name}:latest"
          fi
        done
