FROM gitpod/workspace-bun:latest

ENV PATH="/home/gitpod/.bun/bin:/home/gitpod/.local/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ENV TRIGGER_REBUILD="1"
ENV LANG="en_US.UTF-8"
ENV HOME="/home/gitpod"
ENV BUN_INSTALL="/home/gitpod/.bun"
ENV BUN_VERSION="1.1.27"

CMD ["/bin/bash"]