name: "Build and Push Containers"
description: "Builds and pushes container images to all registries"

inputs:
  version-map:
    description: "JSON map of container names to versions"
    required: true
  affected-containers:
    description: "Comma-separated list of affected containers"
    required: true
  github-registry:
    description: "GitHub container registry URL"
    required: true
  gitlab-registry:
    description: "GitLab container registry URL"
    required: true
  dockerhub-username:
    description: "Docker Hub username"
    required: true
  repository-name:
    description: "Repository name"
    required: true

outputs:
  build-success:
    description: "Whether the build was successful"
    value: ${{ steps.build.outputs.success }}

runs:
  using: "composite"
  steps:
    - name: Build and push containers
      id: build
      shell: bash
      env:
        VERSION_MAP: ${{ inputs.version-map }}
        AFFECTED_CONTAINERS: ${{ inputs.affected-containers }}
        GITHUB_REGISTRY: ${{ inputs.github-registry }}
        GITLAB_REGISTRY: ${{ inputs.gitlab-registry }}
        GL_USERNAME: ${{ inputs.dockerhub-username }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        REPOSITORY_NAME: ${{ inputs.repository-name }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        GITHUB_RUN_ID: ${{ github.run_id }}
      run: |
        echo "🔨 Building containers..."
        echo "📦 Version map: $VERSION_MAP"
        echo "📋 Affected containers: $AFFECTED_CONTAINERS"

        chmod +x scripts/build-containers.sh

        if ./scripts/build-containers.sh; then
          echo "success=true" >> $GITHUB_OUTPUT
          echo "✅ All containers built successfully"
        else
          echo "success=false" >> $GITHUB_OUTPUT
          echo "❌ Container build failed"
        fi
