name: "Update Documentation"
description: "Updates README files with image sizes and syncs changes"

inputs:
  gitlab-token:
    description: "GitLab token"
    required: true
  ref-name:
    description: "Git reference name"
    required: true
  github-token:
    description: "GitHub token"
    required: true
  version:
    description: "Release version"
    required: true
  dockerhub-token:
    description: "Dockerhub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Update image sizes
      shell: bash
      run: |
        echo "GITLAB_TOKEN=${{ inputs.gitlab-token }}" > .env
        echo "GH_TOKEN=${{ inputs.github-token }}" >> .env
        echo "DOCKERHUB_TOKEN=${{ inputs.dockerhub-token }}" >> .env
        bun run s && bun run f

    - name: Commit documentation changes
      shell: bash
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git remote set-url origin https://${{ inputs.github-token }}@github.com/${GITHUB_REPOSITORY}.git
        git add README.md base/*/README.md
        git commit -m "docs: update image sizes for version ${{ inputs.version }}"
        git push origin HEAD:${{ inputs.ref-name }}