name: "Update Documentation"
description: "Update README files and push changes"

inputs:
  gitlab-token:
    description: "GitLab token"
    required: true
  repo-owner:
    description: "Repository owner"
    required: true
  ref-name:
    description: "Git reference name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Update image sizes
      shell: bash
      run: |
        echo "GITLAB_TOKEN=${{ inputs.gitlab-token }}" > .env
        npm run s && npm run f

    - name: Commit README updates
      shell: bash
      run: |
        git config --global user.email "${{ inputs.repo-owner }}@users.noreply.github.com"
        git config --global user.name "${{ inputs.repo-owner }}"
        git add README.md base/*/README.md
        git commit --amend --no-edit
        git push -f origin HEAD:${{ inputs.ref-name }}

        git remote add gitlab https://oauth2:${{ inputs.gitlab-token }}@gitlab.com/${GITLAB_PROJECT_PATH}.git
        git push -f gitlab HEAD:${{ inputs.ref-name }}
