name: "Update Documentation"
description: "Updates README files with image sizes, commits, and pushes changes"

inputs:
  gitlab-token:
    description: "GitLab token"
    required: false
  github-token:
    description: "GitHub token"
    required: true
  dockerhub-token:
    description: "DockerHub token"
    required: false
  version-map:
    description: "JSON map of container versions for commit message"
    required: false
    default: "{}"
  skip-commit:
    description: "Skip commit and push steps (for testing)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Update image sizes
      shell: bash
      env:
        GITLAB_TOKEN: ${{ inputs.gitlab-token }}
        GH_TOKEN: ${{ inputs.github-token }}
        DOCKERHUB_TOKEN: ${{ inputs.dockerhub-token }}
      run: |
        bun run s && bun run f

    - name: Commit and push documentation changes
      if: inputs.skip-commit != 'true'
      uses: ./.github/actions/git-operations
      with:
        github-token: ${{ inputs.github-token }}
        files-to-stage: "README.md CHANGELOG.md docs/IMAGE_VARIANTS.md"
        commit-message: "docs: update documentation [skip ci]"
        version-map: ${{ inputs.version-map }}
        commit-body: |-
          - Updated CHANGELOG.md with container versions and tool information
          - Updated README files with latest image sizes
        skip-if-no-changes: "true"
        auto-pull-before-push: "true"
        branch: "main"
