name: "Update Documentation"
description: "Updates README files with image sizes and syncs changes"

inputs:
  gitlab-token:
    description: "GitLab token"
    required: false
  github-token:
    description: "GitHub token"
    required: true
  dockerhub-token:
    description: "DockerHub token"
    required: false

runs:
  using: "composite"
  steps:
    - name: Update image sizes
      shell: bash
      run: |
        echo "GITLAB_TOKEN=${{ inputs.gitlab-token }}" > .env
        echo "GH_TOKEN=${{ inputs.github-token }}" >> .env
        echo "DOCKERHUB_TOKEN=${{ inputs.dockerhub-token }}" >> .env
        bun run s && bun run f

    - name: Stage documentation changes
      shell: bash
      run: |
        git config --global user.email "${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git add README.md CHANGELOG.md docs/IMAGE_VARIANTS.md 2>/dev/null || true
