name: "Update Documentation"
description: "Updates README files with image sizes and syncs changes"

inputs:
  gitlab-token:
    description: "GitLab token"
    required: true
  ref-name:
    description: "Git reference name"
    required: true
  github-token:
    description: "GitHub token"
    required: true
  version:
    description: "Release version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Update image sizes
      shell: bash
      run: |
        echo "GITLAB_TOKEN=${{ inputs.gitlab-token }}" > .env
        echo "GH_TOKEN=${{ inputs.github-token }}" >> .env
        npm run s && npm run f

    - name: Update commit and force push
      shell: bash
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git remote set-url origin https://${{ inputs.github-token }}@github.com/${GITHUB_REPOSITORY}.git
        git add README.md base/*/README.md
        git commit --amend --no-edit
        git tag -f v${{ inputs.version }}
        git push -f origin HEAD:${{ inputs.ref-name }} +v${{ inputs.version }}
