name: Build and Publish DevContainers

on:
  push:
    branches: [ main ]
    paths:
      - 'base/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'base/**'
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push DevContainer images
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY: ${{ github.repository }}
          SHA: ${{ github.sha }}
        run: |
          for dir in base/*/; do
            devcontainer_name=$(basename "$dir")
            if [ -f "$dir/.devcontainer/Dockerfile" ]; then
              docker buildx build \
                --file "$dir/.devcontainer/Dockerfile" \
                --push=${{ github.event_name != 'pull_request' }} \
                --tag "${REGISTRY}/${REPOSITORY}/${devcontainer_name}:latest" \
                --tag "${REGISTRY}/${REPOSITORY}/${devcontainer_name}:${SHA}" \
                "$dir/.devcontainer"
            else
              echo "No Dockerfile found in $dir/.devcontainer"
            fi
          done

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          branch: main
