name: Sync to GitLab

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  sync:
    if: "!contains(github.event.head_commit.message, 'GitLab Sync') && !contains(github.event.head_commit.message, 'Release')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with GitLab
        run: |
          git config user.name "vikshan"
          git config user.email "vixshan@gmail.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/vikshan/devcontainers.git

          for branch in $(git branch -r | grep 'origin/' | sed 's/origin//'); do
            git checkout -B "$branch" "origin/$branch"
            git commit --allow-empty -m "GitHub Sync: ${{ github.event.head_commit.message }}"
            git push -f gitlab "$branch:$branch"
          done
