name: Release DevContainers

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "base/**"

env:
  GITHUB_REGISTRY: ghcr.io
  GITLAB_REGISTRY: registry.gitlab.com
  GH_REPO: ${{ github.repository }}
  REPO_NAME: ${{ github.event.repository.name }}
  GITHUB_USERNAME: ${{ github.repository_owner }}
  GITLAB_USERNAME: vikshan

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node and Bun
        uses: iamvikshan/.github/.github/actions/setup-node-bun@main

      - name: Configure Container Registries
        uses: ./.github/actions/configure-registries
        with:
          github-token: ${{ secrets.GH_PAT }}
          gitlab-token: ${{ secrets.GITLAB_TOKEN }}
          github-owner: ${{ github.repository_owner }}

      - name: Release
        uses: ./.github/actions/release-containers
        with:
          gh-token: ${{ secrets.GH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gitlab-token: ${{ secrets.GITLAB_TOKEN }}
          repo-owner: ${{ github.repository_owner }}

      - name: Build and Push Containers
        uses: ./.github/actions/build-containers
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gitlab-token: ${{ secrets.GITLAB_TOKEN }}

      - name: Update Documentation
        uses: ./.github/actions/update-docs
        with:
          gitlab-token: ${{ secrets.GITLAB_TOKEN }}
          repo-owner: ${{ github.repository_owner }}
          ref-name: ${{ github.ref_name }}
